repositorie: #TODO
  adelie_current: #TODO
  aix_osp: #TODO
  aixtoolbox: #TODO
  almalinux_8: #TODO
  alpine_3_8: apk
  alpine_3_9: apk
  alpine_3_10: apk
  alpine_3_11: apk
  alpine_3_12: apk
  alpine_3_13: apk
  alpine_3_14: apk
  alpine_edge: apk
  alt_p9: #TODO
  altsisyphus: #TODO
  amazon_1: #TODO
  amazon_2: #TODO
  antix_jessie: #TODO
  antix_17: #TODO
  antix_19: #TODO
  aosc: #TODO
  apertis_v2020: #TODO
  apertis_v2021: #TODO
  apertis_v2022: #TODO
  appget: #TODO
  arch: pacman
  arch_testing: pacman
  aur: paru
  artix: pacman
  astra_stable: #TODO
  astra_current: #TODO
  ataraxia: #TODO
  backbox_6: apt
  backbox_7: apt
  blackarch: pacman
  buckaroo: #TODO
  bunsenlabs_hydrogen: apt
  bunsenlabs_jessie_backports: apt
  bunsenlabs_helium: apt
  bunsenlabs_stretch_backports: apt
  calculate: emerge
  carbs: #TODO
  centos_6: yum
  centos_7: yum
  centos_8: yum
  chakra: #TODO
  chakra_staging: #TODO
  chakra_testing: #TODO
  chaotic-aur: #TODO
  chocolatey: #TODO
  conancenter: #TODO
  cpan: #TODO
  metacpan: #TODO
  cran: #TODO
  crates_io: #TODO
  crux_34: #TODO
  crux_35: #TODO
  crux_36: #TODO
  cygwin: #TODO
  deb_multimedia_unstable: #TODO
  debian_oldstable: apt
  debian_stable: apt
  debian_stable_backports: apt
  debian_testing: apt
  debian_unstable: apt
  debian_experimental: apt
  deepin_unstable: apt
  devuan_1_0: apt
  devuan_2_0: apt
  devuan_3_0: apt
  devuan_4_0: apt
  devuan_unstable: apt
  distri: #TODO
  distrowatch: #TODO
  dports: #TODO
  elrepo_el7: #TODO
  elrepo_el7_testing: #TODO
  entware: #TODO
  epel_6: #TODO
  epel_7: #TODO
  epel_8: #TODO
  exherbo: #TODO
  fdroid: #TODO
  fedora_26: dnf
  fedora_27: dnf
  fedora_28: dnf
  fedora_29: dnf
  fedora_30: dnf
  fedora_31: dnf
  fedora_32: dnf
  fedora_33: dnf
  fedora_34: dnf
  fedora_rawhide: dnf
  freebsd: pkg
  freshcode: #TODO
  funtoo_1.4: #TODO
  gentoo: emerge
  gentoo_ovl_guru: emerge
  gentoo_ovl_pentoo: emerge
  gentoo_ovl_science: emerge
  gnu_elpa: #TODO
  gnuguix: #TODO
  gobolinux: #TODO
  hackage: #TODO
  haikuports_master: #TODO
  homebrew: brew
  homebrew_casks: brew
  homebrew_tap_brewsci_bio: brew
  hpux_11_31: #TODO
  hyperbola: #TODO
  ibmi: #TODO
  just-install: #TODO
  kali_rolling: #TODO
  kaos: #TODO
  kaos_build: #TODO
  kaos_kde_next: #TODO
  kde_neon_dev_stable: apt
  kde_neon_dev_unstable: apt
  kde_neon_user: apt
  kde_neon_user_lts: apt
  kiss_games: #TODO
  kiss_main: #TODO
  libregamewiki: #TODO
  liguros_stable: #TODO
  liguros_develop: #TODO
  linux_mint_17: apt
  linux_mint_17_1: apt
  linux_mint_17_2: apt
  linux_mint_17_3: apt
  linux_mint_18: apt
  linux_mint_18_1: apt
  linux_mint_18_2: apt
  linux_mint_18_3: apt
  linux_mint_19: apt
  linux_mint_19_1: apt
  linux_mint_19_2: apt
  linux_mint_19_3: apt
  linux_mint_20_0: apt
  linux_mint_20_1: apt
  linux_mint_20_2: apt
  linuxbrew: brew
  lmde_4: #TODO
  luarocks: #TODO
  macports: port
  maemo_fremantle: #TODO
  mageia_7: urpmi
  mageia_8: urpmi
  mageia_cauldron: urpmi
  manjaro_stable: pacman
  manjaro_testing: pacman
  manjaro_unstable: pacman
  melpa: #TODO
  melpa_stable: #TODO
  mports: mports
  msys2_mingw: #TODO
  msys2_msys2: #TODO
  mx_15: apt
  mx_15_testing: apt
  mx_16: apt
  mx_17: apt
  mx_17_testing: apt
  mx_19: apt
  mx_19_testing: apt
  neurodebian_data: apt
  neurodebian_debian_8: apt
  neurodebian_debian_9: apt
  neurodebian_debian_10: apt
  neurodebian_debian_unstable: apt
  neurodebian_ubuntu_14_04: apt
  neurodebian_ubuntu_16_04: apt
  neurodebian_ubuntu_18_04: apt
  neurodebian_ubuntu_19_04: apt
  nix_stable: nix-env
  nix_unstable: nix-env
  npackd_stable: #TODO
  npackd_stable64: #TODO
  npackd_unstable: #TODO
  openbsd: pkg_add
  openeuler_20_03: #TODO
  openindiana: #TODO
  openmamba: #TODO
  openmandriva_4: #TODO
  openmandriva_cooker: #TODO
  openpkg_current: #TODO
  opensuse_leap_42_3: zypper
  opensuse_leap_15_0: zypper
  opensuse_leap_15_1: zypper
  opensuse_leap_15_2: zypper
  opensuse_leap_15_3: zypper
  opensuse_tumbleweed: zypper
  opensuse_education_tumbleweed: zypper
  opensuse_emulators_tumbleweed: zypper
  opensuse_games_tumbleweed: zypper
  opensuse_graphics_tumbleweed: zypper
  opensuse_hardware_sdr_tumbleweed: zypper
  opensuse_multimedia_apps_tumbleweed: zypper
  opensuse_multimedia_libs_tumbleweed: zypper
  opensuse_network_tumbleweed: zypper
  opensuse_science_tumbleweed: zypper
  opensuse_security_tumbleweed: zypper
  openwrt_17_01_x86_64: #TODO
  openwrt_18_06_x86_64: #TODO
  openwrt_19_07_x86_64: #TODO
  os4depot: #TODO
  packman_opensuse_leap_42_3: zypper
  packman_opensuse_leap_15_0: zypper
  packman_opensuse_leap_15_1: zypper
  packman_opensuse_leap_15_2: zypper
  packman_opensuse_tumbleweed: zypper
  packman_sle_12: zypper
  packman_sle_15: zypper
  parabola: pacman
  parabola_testing: pacman
  pardus_17: #TODO
  pardus_19: #TODO
  parrot: #TODO
  pclinuxos: #TODO
  pisi_main: #TODO
  pisi_contrib: #TODO
  pkgsrc_current: pkgin
  pld: #TODO
  postmarketos_20.05: #TODO
  postmarketos_21.03: #TODO
  postmarketos_master: #TODO
  pureos_amber: #TODO
  pureos_landing: #TODO
  pypi: pip
  raspbian_oldstable: #TODO
  raspbian_stable: #TODO
  raspbian_testing: #TODO
  ravenports: #TODO
  reactos: #TODO
  rebornos: #TODO
  rocky_8: #TODO
  rosa_2014_1: #TODO
  rosa_2016_1: #TODO
  rosa_2019_1: #TODO
  rosa_server_6_9: #TODO
  rosa_server_7_3: #TODO
  rosa_server_7_5: #TODO
  rpmfusion_el_6: #TODO
  rpmfusion_el_7: #TODO
  rpmfusion_el_8: #TODO
  rpmfusion_fedora_31: #TODO
  rpmfusion_fedora_32: #TODO
  rpmfusion_fedora_33: #TODO
  rpmfusion_fedora_rawhide: #TODO
  rpmsphere: #TODO
  rubygems: #TODO
  sabayon: #TODO
  sabayon_for_gentoo: #TODO
  sagemath_stable: #TODO
  sagemath_develop: #TODO
  salix_14_2: #TODO
  scientific_7x: #TODO
  sclo: #TODO
  scoop: #TODO
  siduction_unstable: #TODO
  siduction_experimental: #TODO
  slackbuilds: slackpkg
  slackware_14_2: slackpkg
  slackware_current: slackpkg
  slackware64_14_2: slackpkg
  slackware64_current: slackpkg
  slackwarearm_14_2: slackpkg
  slackwarearm_current: slackpkg
  slitaz_cooking: #TODO
  slitaz_next: #TODO
  solus: eopkg
  sparky_stable: #TODO
  sparky_testing: #TODO
  stackage_lts: #TODO
  stackage_nighly: #TODO
  t2: #TODO
  tails_stable: #TODO
  tails_devel: #TODO
  termux: termux-setup-storage
  trisquel_6_0: #TODO
  trisquel_6_0_backports: #TODO
  trisquel_7_0: #TODO
  trisquel_7_0_backports: #TODO
  trisquel_8_0: #TODO
  trisquel_8_0_backports: #TODO
  trisquel_9_0: #TODO
  trisquel_9_0_backports: #TODO
  ubi_8: #TODO
  ubuntu_14_04: apt
  ubuntu_14_04_backports: apt
  ubuntu_16_04: apt
  ubuntu_16_04_backports: apt
  ubuntu_18_04: apt
  ubuntu_18_04_backports: apt
  ubuntu_20_04: apt
  ubuntu_20_04_backports: apt
  ubuntu_20_10: apt
  ubuntu_20_10_backports: apt
  ubuntu_21_04: apt
  ubuntu_21_04_proposed: apt
  unitedrpms_32: #TODO
  unitedrpms_33: #TODO
  unitedrpms_34: #TODO
  unitedrpms_35: #TODO
  vcpkg: #TODO
  void_x86_64: xbps-install
  wikidata: #TODO
  winget: #TODO
  yacp: #TODO

package_manager: #TODO
  apk: "{permission_tool} apk add"
  apt: "{permission_tool} apt install --assume-yes"
  dnf: "{permission_tool} dnf install --assumeyes"
  eopkg: "{permission_tool} eopkg install --yes-all"
  mports: "{permission_tool} mports install"
  pkg_add: "{permission_tool} pkg_add -I"
  pacman: "{permission_tool} pacman --sync --noconfirm --needed"
  emerge: "{permission_tool} emerge"
  pkgin: "{permission_tool} pkgin install -y"
  pkg: "{permission_tool} pkg install -y"
  slackpkg: "{permission_tool} slackpkg install"
  termux-setup-storage: "pkg install --assume-yes" #TODO
  urpmi: "{permission_tool} urpmi --force"
  xbps-install: "{permission_tool} xbps-install --yes"
  yum: "{permission_tool} yum install --assumeyes"
  zypper: "{permission_tool} zypper --non-interactive install"

  paru: "paru --sync --skipreview --useask --noconfirm --needed"
  flatpak: "{permission_tool} flatpak install"
  brew: "brew install"
  port: "{permission_tool} port install"
  nix-env: "NIXPKGS_ALLOW_UNFREE='1' nix-env --install --attr"
  sbopkg: "{permission_tool} sbopkg -ifq"
  snap: "{permission_tool} snap install"

  npm: "{permission_tool} npm install --global"
  pip: "pip install --user"
  yarn: "yarn global add"
